- name: Get application from git to build
  hosts: localhost
  gather_facts: no
  vars:
      app_server_ip: 
      build_repo: https://github.com/bachadir/segmentify_app.git
      build_version: Version-1
      ssh_key_location: /root/.ssh/google
      ssh_user: bahadirtasdelen_gmail_com
  tasks:
   - name: Deployment
     ansible.builtin.git:
         repo: '{{ build_repo }}'
         dest: ./segmentify_app
         version: '{{ build_version }}'
   - name: Build application
     ansible.builtin.command:
         cmd: go build -o ./segmentify_app/helloworld ./segmentify_app/main.go 
         creates: ./segmentify_app/helloworld
   - name: Deploy to server 
     ansible.builtin.command:
         cmd: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ssh_key_location }} ./segmentify_app/helloworld {{ ssh_user }}@{{ app_server_ip }}:/home/{{ ssh_user }}
   - name: Start the service
     ansible.builtin.command:
         cmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ssh_key_location }}  {{ ssh_user }}@{{ app_server_ip }} 'sudo systemctl restart helloworld.service'
   - name: Wait for http to come up
         wait_for: host={{ app_server_ip }} port=80 delay=10 timeout=60